#!/bin/sh

set -e

if [ "upgrade" = "$1" ] ; then
  if dpkg --compare-versions "$2" lt '0.10.0' ; then
    rm -f /usr/bin/gcc
	  rm -f /usr/bin/g++
	  dpkg-divert --package apt-build --remove --rename /usr/bin/gcc
	  dpkg-divert --package apt-build --remove --rename /usr/bin/g++
  fi
fi

# remove obsolete config file from apt-build <= 0.12.37
if dpkg-maintscript-helper supports rm_conffile 2>/dev/null ; then
  dpkg-maintscript-helper rm_conffile /etc/apt/sources.list.d/apt-build -- "$@"
fi

#DEBHELPER#
